Fix/mudanca imagem role ubuntu
mentoriaiac/template-role-ansible pull request #13
Opened 2022-03-30 01:56 UTC by afernandescneto

# Utiliza Ubuntu como imagem padrão

Foi realizada a mudança da imagem da role. 

- [X] Garanta que seu **topic/feature/bugfix branch** tenha uma branch nomeada e não a sua branch main esteja no PR
- [X] Dê um titulo que expresse o objetivo do PR
- [X] Associe seu PR a uma Issue criada no repositósito. Caso seja uma correção de linguagem ou pequenas correções, não é necessário
- [X] Descreva o objetivo do PR
- [X] Inclua links relevantes para a sua modificação/sugestão/correção
- [X] Descreva um passo-a-passo para testar o seu PR

## Issue

#8 

## Objetivo

O template estava usando CentOS como imagem padrão, mas estava sendo modificada sempre que usado para Ubuntu. Essa mudança faz com que use o Ubuntu por padrão. 

## Referências

Usado como base para referência da imagem:
https://github.com/mentoriaiac/iac_role_nginx/blob/main/molecule/default/molecule.yml

## Como testar
Usar o seguinte comando:
```bash
molecule test
```

2022-03-30 22:16 UTC, gomex requested changes
Gostei das mudanças, mas pensei que talvez possamos usar essa chance pra atualizar os pacotes do python.

2022-03-30 22:16 UTC, gomex commented on requirements.txt
>  ansible==2.10.5
O que acha de aproveitar e atualizar logo para os pacotes mais novos?

2022-03-31 11:43 UTC, afernandescneto commented on requirements.txt
>  ansible==2.10.5
Realmente. Focamos na resolução e nem nos atentamos a essa possibilidade. Vou verificar com Cleyton (cflb) para resolvermos isso.

2022-04-02 17:31 UTC, gomex commented on requirements.txt
>  ansible==2.10.5
Uma solução pode ser pegar esse requirements.txt e usar aqui: https://github.com/mentoriaiac/iac_role_consul/blob/main/requirements.txt

2022-04-09 23:47 UTC, lgfa29 commented on requirements.txt
>  ansible==2.10.5
Atualizado para 5.6.0.

2022-04-10 16:39 UTC, gomex approved these changes
LGTM

2022-04-10 16:39 UTC, merged